language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -U pip
  - pip install -r dev-requirements.txt
  - pip install -e git+https://github.com/shuup/shuup.git@master#egg=shuup
  - pip install -e .
script:
  - isort --check-only
  - flake8
  - py.test -ra -vvv --cov-config .coveragerc --cov shuup_recommender shuup_recommender_tests
after_success: coveralls
